### ISSUE TITLE
Unable to disable

### ISSUE THREAD

**Issue by anohren** [MediaBrowser/plugin.video.emby#104]
When trying to disable the plugin 2.3.55, installed on an up-to-date osmc on pi 3, Kodi becomes unresponsive.

**Comment by angelblue05** [comment]
Are you saying that even if Kodi becomes unresponsive (which is expected, it's a service add-on), once your start Kodi again, the add-on is still enabled?

**Comment by anohren** [comment]
That is a good question. No, it becomes disabled after restart. 

However I disagree that it was expected — but as long as you know about it.

**Comment by angelblue05** [comment]
It is expected for service addons because they permanently run until Kodi is shut down or the profile is changed. There's no event triggering when the addon is disabled. Kodi tries to terminate the addon which is running, causing the freeze. Simple as that.

**Comment by anohren** [comment]
Thanks. 

Perhaps you meant to say that it's intended behavior, which I can understand. There's no way to make a user expect the program to freeze though, unless the button is labeled "freeze program", so it's still far from expected. 

I take it that Kodi's architecture is the culprit then.

**Comment by angelblue05** [comment]
Ah yes. Well my English is not perfect. You got me there :)

Intended, yes. Yeah, but as long as disabling works, then there's nothing to be concerned about.

**Comment by anohren** [comment]
No worries, whose is? Thanks for the explanation. 

Now to install the server and actually trying this thing out...
