### ISSUE TITLE
Kodi for Emby Addon playback issue

### ISSUE THREAD

**Issue by CWGSM3V0** [MediaBrowser/plugin.video.emby#111]
Was running 2.3.59 (or .57) and noticed I auto-updated to 2.3.60 and now playback is affected. I've tried enabling debug logging on the addon side and server-side but nothing obvious comes up except the error itself. I'm more than happy to provide more captures if I know the appropriate procedure. Here's what I captured so far that I felt was relevant to warrant this posting:

18:15:49.735 T:545002053856  NOTICE: EMBY.default_tvshows -> Parameter string: ?dbid=3560&mode=play&id=eafccbcac337b819a1c163e1ce946215&filename=S05E21+-+Stargate+SG-1+-+Meridian.avi
18:15:52.640 T:545002053856  NOTICE: EMBY.playbackutils -> Play called.
18:15:52.677 T:545002053856  NOTICE: EMBY.playutils -> Can't direct play, play from HTTP enabled.
18:15:52.685 T:545002053856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('Profile',)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.emby.tvshows/default.py", line 50, in <module>
                                                entrypoint.doPlayback(itemid, dbid)
                                              File "/storage/.kodi/addons/plugin.video.emby/resources/lib/entrypoint.py", line 46, in doPlayback
                                                pbutils.PlaybackUtils(item).play(itemId, dbId)
                                              File "/storage/.kodi/addons/plugin.video.emby/resources/lib/playbackutils.py", line 57, in play
                                                playurl = playutils.getPlayUrl()
                                              File "/storage/.kodi/addons/plugin.video.emby/resources/lib/playutils.py", line 102, in getPlayUrl
                                                elif self.isDirectStream():
                                              File "/storage/.kodi/addons/plugin.video.emby/resources/lib/playutils.py", line 249, in isDirectStream
                                                videoprofile = self.item['MediaStreams'][vid]['Profile']
                                            KeyError: ('Profile',)
                                            -->End of Python script error report<--
18:15:53.020 T:545002053856 WARNING: CPythonInvoker(83, /storage/.kodi/addons/plugin.video.emby.tvshows/default.py): the python script "/storage/.kodi/addons/plugin.video.emby.tvshows/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
18:15:53.065 T:548174741504   ERROR: Playlist Player: skipping unplayable item: 20, path [plugin://plugin.video.emby.tvshows/19d17c1bb7ee5db035162639989c8f72/?dbid=3560&mode=play&id=eafccbcac337b819a1c163e1ce946215&filename=S05E21+-+Stargate+SG-1+-+Meridian.avi]
18:15:54.740 T:546861740256  NOTICE: EMBY.kodimonitor -> Method: Playlist.OnClear Data: {"playlistid":1}

Now even files I've previously watched (complete or otherwise) will no longer play. It seems somewhat random and not really sure where to begin. I've reinstalled the addon/Kodi and even tried older versions without any luck. I copied the videos in question to my local machine and added them as local content, they play fine this way. I can play the content from the Emby web-viewer/player without issue. Checked permissions. This seems to be isolated to the addon and I've run out of ideas how to troubleshoot.

I've even removed the library in question and re-added it back, same result. Not all content is affected, in fact, it's only this one area of tv shows (Stargate SG-1) and some episodes play, others generate exactly the same error above.

Looking for any help I can get and do whatever I can to help provide the right kind of debugging information you may need.

**Comment by angelblue05** [comment]
Use the latest 2.3.61.

**Comment by angelblue05** [comment]
Sorry I just saw your comment. Yes, it should be fine for now, thank you :)

**Comment by CWGSM3V0** [comment]
Thanks!
