### ISSUE TITLE
artworks being queried really(too) often 

### ISSUE THREAD

**Issue by farfromrefug** [MediaBrowser/plugin.video.emby#122]
Hi,

I have emby server running on a pretty slow Synology.
It works great except that image transfer over http is sometimes quite long, but most of all it seems to be requested a LOT.
So i decided to take a look at the code to understand.
For example i can see [here](https://github.com/MediaBrowser/plugin.video.emby/blob/68f959580b1b51474308ef02e498bbbccb40e4bc/resources/lib/playbackutils.py#L55) that even for items already in database, all artworks are requested to the server through  ```play/set_playlist/set_properties/set_artwork/artwork.get_all_artwork```. Am i wrong?
If not that seems really heavy.

Could we have an option at least to only update artworks when necessary (which should be item add, or in some cases update)?

Thanks

**Comment by angelblue05** [comment]
No it is not possible. If it's too demanding, just switch to native playback mode and reset your local database to apply the change.

Things are in place because some artwork doesn't fill correctly when playing content.

**Comment by farfromrefug** [comment]
@angelblue05 when you speak of native playback you mean direct stream in emby? That s what i am already using.

**Comment by angelblue05** [comment]
No not at all. I mean, in the add-on settings > sync option > Set playback mode to native. This will leave it all up to Kodi instead of using the add-on for playback. It should stop the artwork query upon playback.

**Comment by farfromrefug** [comment]
@angelblue05 Thanks for the explanation. I already had the plugin setup the right way. 
Now i still see a lot of image querying even while not syncing and while kodi seems to already have the image. Will have to investigate more.
Will try and continue that discussion on the forum. 
Thanks again for all your help!
