### ISSUE TITLE
[FR]option to disable GoogleAnalytics

### ISSUE THREAD

**Issue by farfromrefug** [MediaBrowser/plugin.video.emby#124]
Hi,
I really think it should be good to have an option to disable google analytics. I don't really like my watching habits to go through google...

**Comment by angelblue05** [comment]
No identifying information is sent. You can already disable it via the add-on settings > advanced > Disable analytic metric logging.

**Comment by farfromrefug** [comment]
@angelblue05 great thanks missed that option.

**Comment by im85288** [comment]
It probably should be turned off by default with an option to opt in. Official kodi addons are not allowed to use this so might be a more friendly way of approaching this

**Comment by angelblue05** [comment]
The add-on will never be part of the official repo, so I'm not concerned by it. There's a way to disable it, that's all that matters.

**Comment by angelblue05** [comment]
If anything, I'm more likely to rip it out of the code :) less code, less maintenance for me.
