### ISSUE TITLE
Sync failed when addon auto updates itself

### ISSUE THREAD

**Issue by popy2k14** [MediaBrowser/plugin.video.emby#133]
Hi, 

Had  an issue recently,  that the addon updated itself to 3.0.28a from 3.0.27a. 
My kodi build was windows x64 from 02.06.2018. After the addon update, emby for kodi refuses to sync with an error. 

In the database folder the was a MyVideos109.db which was ~14mb and the 110.db which was 0 byte. 

Also when I deleted all the MyVideosXXX.db files the sync was not functional. 

After I have noticed, that kodi has updated the Db to v110,I have updated it to the current master build and emby 3.0.28a started working again. 

So here is my idea: why don't make emby for  kodi detect the dB version and uses an adaptive scheme (added, removed columns...)? 

What you are thinking of my idea?

**Comment by angelblue05** [comment]
I know it's been a while, adaptive schemes is part of beta, soon to be part of stable.

**Comment by popy2k14** [comment]
Nice to hear that. Thx a lot for your efforts
