### ISSUE TITLE
Option to not login to Emby masterprofile account on multi user setups

### ISSUE THREAD

**Issue by anoma** [MediaBrowser/plugin.video.emby#136]
If you are using Kodi profiles the recommended/sensible option is to add one new Kodi profile to match each username defined in Emby. This works as intended.

However the Kodi default user, `MasterProfile`, controls all the installation and update of all local Kodi plugins and is not a Emby user.

Since the `MasterProfile`  (essentially the root account of the Kodi GUI with permissions to add and remove addons that impact all other local users) does not have a reciprocal Emby profile this causes issues as the plugin.video.emby addon does not understand the concept of the addon being enabled but not tied to an Emby user.

The symptoms:

When installing the Emby addon, if you cancel the registration of the `MasterProfile` Kodi user to the Emby user via the normal popup dialogue Kodi locks up. You can eventually disable the plugin.video.emby addon in this profile which has no impact on other local Kodi user which can happily keep using the addon.

However this means that the addon never updates for any user and get stuck at the version used when first installed.

The only way I can see around this is to

* Consume and maintain a fake user in Emby tied to the Kodi `MasterProfile`. Whilst this is obviously possible its not very elegant.
* Alter this addon to accept the concept of being installed, enabled but not tied to an Emby account

**Comment by anoma** [comment]
Re-confirmed with 3.0.34.

When updating the addon there is no option to opt out of connecting to a Emby server. If you then disable the addon Kodi on LibreELEC locks up completely.

On hard restart the addon is updated and disabled as intended

**Comment by anoma** [comment]
Re-confirmed with 3.1.35a.

**Comment by angelblue05** [comment]
@anoma isn't it possible this is an issue with the Kodi profile system? The add-on has no awareness of being enabled or not.

**Comment by angelblue05** [comment]
Ok I will see what I can do about this before next stable.

**Comment by anoma** [comment]
Very much appreciated. FWIW i have just reconfirmed this on 44a.

The ideal scenario is there is a state where the addon is enabled in kodi but it is set to not connect. The authentication method drop down where you choose Emby connect/password etc (sorry forget the exact setting name) might be a good home for a `Do not connect` option.

This way Kodi will auto update the addon which obviously it wont currently.

**Comment by angelblue05** [comment]
I've added an option to disable Emby for Kodi in the add-on settings. The add-on will still be enabled in Kodi, but will not run. That should be good enough right?
https://github.com/MediaBrowser/plugin.video.emby/pull/171

**Comment by anoma** [comment]
Just to follow up this new feature seems to be working perfectly.
