### ISSUE TITLE
Only last logged in user remembered when using Kodi profiles

### ISSUE THREAD

**Issue by amkay** [MediaBrowser/plugin.video.emby#142]
Steps to reproduce:

1. Log in with Emby user A in "Master user" Kodi profile (the default profile that comes with Kodi)
2. Create an additional Kodi profile
3. Switch to the additional Kodi profile
4. Log in with Emby user B
5. Switch to the "Master user" profile again
6. You are logged out of Emby
7. If you log in again, the Emby user in the additional profile is logged out again

See https://emby.media/community/index.php?/topic/62041-kodi-profiles-and-emby-authentication/

**Comment by angelblue05** [comment]
Resolved.
