### ISSUE TITLE
Feature Request: Sync Game DB

### ISSUE THREAD

**Issue by j0nnymoe** [MediaBrowser/plugin.video.emby#146]
As Kodi v18 now supports games via retroplayer, it would be awesome to see the emby addon sync over game libraries from emby into kodi 😄

**Comment by angelblue05** [comment]
Can you send me a pm on the Emby forums? There's little to no documentation on game browser.

**Comment by angelblue05** [comment]
Alright, this is not currently possible with Kodi 18. Maybe with Kodi 19?
