### ISSUE TITLE
Emby plugin messes up my sources.xml

### ISSUE THREAD

**Issue by Glenn-1990** [MediaBrowser/plugin.video.emby#147]
Emby plugin messes with my sources.xml and it deletes all my other files. 
My custom sftp video sources where replaced by this:

```
<sources>
  <video>
    <default pathversion="1" />
    <source>
      <name>Emby</name>
      <path pathversion="1">smb://</path>
      <allowsharing>true</allowsharing>
    </source>
    <source>
      <name>Emby</name>
      <path pathversion="1">smb://</path>
      <allowsharing>true</allowsharing>
    </source>
  </video>
</sources>
```

I don't know if they are necessary for addon mode playback? But if so, the emby sources should be appended instead of replacing the existing ones?

**Comment by angelblue05** [comment]
Yeah it should not be erased. I will ensure that does not happen. I'm actually not sure how that happened, does it still erases the entry if you update a library?

**Comment by Glenn-1990** [comment]
@angelblue05 
I'm using 3.0.34 on Krypton. Somehow I can't reproduce this issue when reinstalling the emby plugin, maybe because some emby settings are left on the hdd when removing?

Can I use the beta addon on Kodi Krypton?

Is editing of sources.xml nessesary and what is the point of adding two empty smb:// sources?
https://github.com/MediaBrowser/plugin.video.emby/blob/d11cb32802bac441b9b9a1c0bbd522c716dd8171/resources/lib/helper/xmls.py#L40

**Comment by angelblue05** [comment]
Sorry I didn't reply sooner, I don't pay as much attention here than I do on the Emby forums. You can use beta on krypton yes.

The point of the entries is to trick Kodi into seeing your library and work properly if you use parental lock settings. With the beta addon however it should not modify existing entries, I've tested it on my side.
