### ISSUE TITLE
Feature Request: Differentiate Hi10p H264 / H265 forced transcoding

### ISSUE THREAD

**Issue by adam111316** [MediaBrowser/plugin.video.emby#148]
My player (Vero 4k+) is able to handle H264 8bit video, and H265 10bit video with no issue.

Playback of H264 10bit is not possible so I am required to enable forced Hi10p transcoding.

When setting "Force Hi10p Transcoding" to True and "Force H265/HEVC Transcoding" to False this causes the H265 bit videos to transcode even though it's not required.

Is it possible to split the Hi10p setting into two e.g. "Force Hi10P transcoding (H264)" and "Force Hi10P transcoding (H265)"?

**Comment by angelblue05** [comment]
That should not be happening, can you provide your Kodi log capturing this?

**Comment by adam111316** [comment]
Refer log here:

https://gist.github.com/adam111316/de62ba15bafec45b03a462cce4cc563f

**Comment by angelblue05** [comment]
I forgot to let you know that this should be fixed. Can you confirm? Thanks.

**Comment by adam111316** [comment]
No luck unfortunately, refer log below:

https://gist.github.com/adam111316/009bd8ed6bab870cb0a3db560a86b4a6
