### ISSUE TITLE
not working on kodi 18 beta4

### ISSUE THREAD

**Issue by dvanmilligan** [MediaBrowser/plugin.video.emby#149]
forgot I was on the beta channel for kodi and was recently  updated to version 18 beta 4, the pugin stopped working and reinstallations did not help. Reverting back to 17.6 resolved it.

**Comment by angelblue05** [comment]
What wasn't working? I'm on beta4 and it works. Did you update the dependencies? Do you have your kodi log?

**Comment by angelblue05** [comment]
Open a new ticket if the issue still exists with RC versions
