### ISSUE TITLE
No option to connect to emby proxyed as subfolder

### ISSUE THREAD

**Issue by anoma** [MediaBrowser/plugin.video.emby#150]
It does not appear possible to enter any variation of settings via the GUI to connect to Emby when it is setup behind a reverse proxy as a subfolder

e.g. https://my.domain/emby/

**Comment by angelblue05** [comment]
@anoma

I'll see to support this in the next version, hopefully before stable is released. Thanks for letting me know of this. In the future, please make a forum post as I don't look at github issues.

**Comment by angelblue05** [comment]
@anoma

I don't understand why it doesn't work. It should. Can you tell me, did you remove the port? All you'd need to do is when it pops up to connect, select add a server manually > https://my.domain/emby/ and make sure there's no port filled.

**Comment by angelblue05** [comment]
Keep me posted. It would be nice to have this resolved if it is indeed broken. I couldn’t test with a real address, but when I entered no port, it was looking to connect at https://my.domain/emby/

**Comment by anoma** [comment]
I have now successfully connected to Emby when it is behind a reverse proxy in a subfolder of a subdomain with SSL with split horizon DNS (probably the most complex example to accommodate e.g. `https://my.example.com/emby/`)

The magic bullet was exactly what you thought it might be @angelblue05 to remove the port setting.

I can only assume with the port entered it is trying to connect to something like `https://my.example.com/emby/:433` but this is pure speculation as i never found the log entry. 

Definite scope for user confusion here although the fix is trivial (and i was sure i tried this before last year)

Let me know if you need me to do any further checking.

**Comment by angelblue05** [comment]
Yes that's exactly what it was trying. It shows up in the bottom "Trying to connect to x" where x is the server looked like https://my.domain/emby/:443

Glad to know this works.
