### ISSUE TITLE
Exploring from TV Shows menu is broken and resets watched status [Kodi 18 RC5] [3.1.43a]

### ISSUE THREAD

**Issue by metronidazole** [MediaBrowser/plugin.video.emby#153]
I'm using Emby for Kodi for the first time and I've encountered a severe bug. Here are my versions:

Emby for Kodi: 3.1.43a
Kodi: 18 RC5
Kodi complement addon (on Emby server)

Whenever I select a TV show from the TV Show menu, and click the browse button within, I get a series of loading circles one after the after, followed by Kodi returning to the TV Shows menu with the TV series I selected having disappeared, and more significantly, my watched status for that TV show being completely reset - both locally and on my emby server. After this, Emby for Kodi starts syncing a number of items for ? reason.

I've tried resetting the database using the option within the addon, but it did not help. I've attached a log of someone attempting to browse "Once Upon A Time" with the addon set to debug logging. 

https://privatebin.net/?99a8d177f16ba2cc#5Eo/Nx/Dif2OmOnAgC3WdPBcMx5TkNPYHNOIAw71B0Q=
Password is eib3bieh3Uk7toy

edit: not sure if it is relevant, but I have been getting an occasional error from the addon stating "unsupported database" (paraphrasing) offering me to continue regardless, but I'm not sure if that's referring to Kodi or the Emby server.

**Comment by angelblue05** [comment]
What are you referring to when you say "the TV Show menu"?

**Comment by metronidazole** [comment]
@angelblue05 The default Kodi theme has menu items e.g. Movies, TV Shows, Videos, Addons, etc. I'm referring to that.

**Comment by angelblue05** [comment]
Can you install 3.1.45

Repair your libraries and let me know if the issue persists.

**Comment by metronidazole** [comment]
@angelblue05 I tried that and now my TV Shows menu doesn't show any shows at all. I will do some further testing and report back with a log.

**Comment by metronidazole** [comment]
How do I check? I can't see any option in settings or under the library menu. If you mean playback mode,, that's set to add-on (default).

I will reset the addon settings completely later tonight and post a log.

**Comment by angelblue05** [comment]
@metronidazole 

Open the Emby for Kodi add-on to show the listing of your libraries and other options to manage your libraries (such as update repair etc). Your TV Show library should display there, is it named TV Show (dynamic)?

**Comment by metronidazole** [comment]
There is no "(dynamic)" tag at the end of my tv show library in Emby for Kodi.

I did a local database reset using the option in your addon settings but that didn't help either. I then enabled debug mode and repaired the library, which didn't help and produced a 170 MB log file. Without debug mode 80 MB log file.

**Comment by angelblue05** [comment]
@metronidazole 

What about your video database file? Is it a reasonable size you could upload somewhere like dropbox? I'm not sure why you are not seeing content. Please reply asap as I'm working on releasing stable and would like to get that fixed before, if possible.

**Comment by metronidazole** [comment]
Log of repair database:

https://privatebin.net/?bb0e673c90bbde5c#OW82WUtUvBVLd7XRBsKH4lhpfFPl7oKfux06LtnV4Q8=
password: joobethiedohhah8ahy8xem9faiDif

**Comment by angelblue05** [comment]
All your shows are missing you say? But it shows as being added in your log. Your log looks absolutely normal. What if you go under videos > tv shows (the Kodi shortcut)?

**Comment by metronidazole** [comment]
Well I recognise that. I'm just reporting my symptoms. Perhaps it's an issue with my kodi installation?

I went to Videos --> TV Shows (Emby) --> TV Shows and it displayed my TV shows. I then went back to menu and returned and they were gone. log here:

https://privatebin.net/?1aea60c2e9a668f4#EeZR65Xai6qU2sWIaO1ERgNA6c4VsAgTQRQ/L0Bt+v4=

Going to Videos -> Tv Shows (kodi) just shows what the main menu of kodi shows under TV shows.

**Comment by angelblue05** [comment]
If you see the content via Videos --> TV Shows (Emby), then your shows are indeed synced.

Videos --> TV Shows (kodi) --> Titles doesn't show your shows at all? Is that correct?

**Comment by metronidazole** [comment]
> If you see the content via Videos --> TV Shows (Emby), then your shows are indeed synced.

It showed it once and then when I backed out and returned to that menu, they were gone.

> Videos --> TV Shows (kodi) --> Titles doesn't show your shows at all? Is that correct?

Correct.

**Comment by angelblue05** [comment]
@metronidazole 
My co-dev tells me you are using an old Estuary clone for Embycon. That is likely why you things are not displaying quite right for Emby for Kodi content. If you change skin, the issue would most likely go away and that would be the quickest way for you to confirm the situation.

**Comment by metronidazole** [comment]
No it's not that, I'm using the default skin. In any case, I figured out what was causing the display bug (parental controls - having a pin setup without hiding anything still hides emby for kodi content) so we can get back to the main issue.

I'm still having the same issue as per the OP. When I open a show and click browse, it still returns to the main kodi menu and deletes all the watched history for that show. Here's a new log showing that for two shows:

https://privatebin.net/?02dd3e167bd6c80a#DpfrJd5fvLq9B6EtbP9EIVD9Li/ASu73MWpxrxsc2Ls=
passsword: joobethiedohhah8ahy8xem9faiDif 

I'm going to bed so I won't be around for another 20 hours or so.

**Comment by sualfred** [comment]
That's a Kodi bug. The button (ID=8) of the info dialog can always be "play"/"resume"/"browse". For some reasons Kodi tries to play the show instead of browsing to the path. 

In Embuary I did a workaround for this, but in your case I suggest you to disable "show information" as default action because this is buggy for widgets anyway.

**Comment by metronidazole** [comment]
Thanks I'll try that later tonight. Is there an option for it to link me to the next episode for every show vs browsing (by season/episode)?

**Comment by angelblue05** [comment]
I am investigating the issue, hopefully it's something we can get sorted. Thank you for your patience. I'll let you know if I find a solution.

**Comment by sualfred** [comment]
@metronidazole 
In the meantime you can switch temporary to my Embuary skin. I use another approach it anyway and you won't see the issue there. "show information" also works as default action for it.

**Comment by angelblue05** [comment]
@metronidazole 
Your issue has been resolved with 4.0.1. Please repair your tv show library to apply the fix once you update to that version of the add-on.
