### ISSUE TITLE
TV show not ticked when watched

### ISSUE THREAD

**Issue by prydda** [MediaBrowser/plugin.video.emby#154]
I was on beta, got promted to updated to stable version and now when a episode is finished it do not show ✓ anymore, 
running coreelec, kodi 18 rc 4.

**Comment by angelblue05** [comment]
No idea what you are talking about, can you give more details? What prompted you to update to stable version. What version of Emby for Kodi are you running?

**Comment by hfredriksson** [comment]
A addon notification prompted me to update to stable version from beta of the emby addon, but I switched back and I'm currently running 3.1.44a.

Like this, the episode wont change to "watched" state with the ✓ icon to the left unless I manually mark it as watched, before it happend instantly when episode ended.
![img_20190120_110914](https://user-images.githubusercontent.com/2561787/51437871-5ce16380-1ca4-11e9-8614-62e9fe87a02a.jpg)

also the half watched episode below is playing from the beginning, not from where I stopped watching, when continuing playing.

**Comment by angelblue05** [comment]
Can you install 3.1.45

Repair your libraries, let me know if the issue persists.

**Comment by hfredriksson** [comment]
It now updates with the ✓ when watched within seconds, thanks! 
The half watched issue is still there tho.

**Comment by prydda** [comment]
Was just about to send you a log and a emby patch had been applied, continue from where I left or w/e it's called now pops up a small emby screen, and I continued watching my series where I left off 👍
