### ISSUE TITLE
Emby Broken?

### ISSUE THREAD

**Issue by MYeager1967** [MediaBrowser/plugin.video.emby#155]
I upgraded the server two days ago and my movies still show up, but all of my TV shows have disappeared. They are still on the server, they just aren't syncing to Kodi...

**Comment by angelblue05** [comment]
Does this help?
https://emby.media/community/index.php?/topic/21888-emby-for-kodi/?p=680481

**Comment by MYeager1967** [comment]
Why, yes it does. Not sure why I didn't find that when I did a quick
search, but that's how it goes. I'll install it tonight and see if the
problem goes away. If not, I'll load up the older version in a docker
container and leave it be...

Thank you!

**Comment by angelblue05** [comment]
I'll assume it's resolved. :)
