### ISSUE TITLE
TV shows with multiple versions show as multiple list entries on kodi

### ISSUE THREAD

**Issue by adam111316** [MediaBrowser/plugin.video.emby#192]
When using the emby convert feature with the setting "Convert to: Original media folder, next to original files", there are duplicate episode listings for the episode in question when synced to kodi.

**Comment by angelblue05** [comment]
I'm not sure how to fix this. Can you provide your Kodi log that captures this? It will depend on if the server triggers an event to update for the original item or not.

If I understand correctly, you have episode A original, that shows in Kodi. Then, you convert but keep the original file, so episode A mod is created, but Emby then stacks episode A original and A mod, but Kodi remains unaware of this fact and displays both episode A.

**Comment by angelblue05** [comment]
This will be fixed with the next version.

**Comment by angelblue05** [comment]
Can you test with the new beta? You'll need to repair (maybe you can update the library instead, under Emby for Kodi > manage libraries) to remove the bad entries. Then moving forward, it should add episodes correctly, but you'll need to test to confirm this. Keep me posted, thank you.

**Comment by adam111316** [comment]
Cheers, works a treat!
