### ISSUE TITLE
HTTP 416 error behind a Squid 3 proxy

### ISSUE THREAD

**Issue by MarinBernard** [MediaBrowser/plugin.video.emby#20]
Hi,

I have just setup the addon on a brand new OpenELEC install. I just wanted to report that the repository website returns an HTTP 416 error when Kodi tries to fetch the repo's main XML file behind a Squid HTTP proxy. Everything works fine as soon as the site is whitelisted to bypass the proxy. Note that this happens with a very simple caching proxy, which doesn't use block lists nor complicated ACL. It seems to be related to your Apache configuration.

Thanks!

**Comment by angelblue05** [comment]
Thank you for reporting, but it's not something we can correct without causing more issues down the line.
