### ISSUE TITLE
Cannot install addon from beta repo

### ISSUE THREAD

**Issue by godfuture** [MediaBrowser/plugin.video.emby#21]
I have installed Kodi on Windows 10 x64. I installed the emby repo as well. Unfortunately the Emby addon is shown as incompatible.
Log says:
```
02:00:21 T:5416   ERROR: CCurlFile::Open failed with code 404 for http://mirrors.kodi.tv/addons/gotham/addons.xml|Encoding=gzip
02:00:21 T:5416   ERROR: XFILE::CFileCache::Open - failed to open source <http://mirrors.kodi.tv/addons/gotham/addons.xml|Encoding=gzip>
02:00:21 T:5416   ERROR: Failed to read directory listing http://mirrors.kodi.tv/addons/gotham/addons.xml for repository repository.xbmc.org.
```

Win10 x64
Emby 3.0.5871.0
Emby for Kodi 2.2.0
Kodi 15.2

**Comment by angelblue05** [comment]
Yeah, if you notice what you pasted, the error is in the Kodi repository. They are having issues, and one of our dependent module is only found in the Kodi repo.

**Comment by angelblue05** [comment]
This should be resolved now. I manually added our Kodi dependency to our Emby repository. So it should be able to install the Emby add-on, even if the Kodi servers are acting up.
