### ISSUE TITLE
Subtitle and language selection

### ISSUE THREAD

**Issue by loeffelpan** [MediaBrowser/plugin.video.emby#221]
Is it possible to enhance Emby for Kodi to play those language and subtitle like selected on emby server, regardless of kodis language settings?
Could only work with addon path, I think.

**Comment by angelblue05** [comment]
It is already in place. However, the server remembers the last selection, so if it’s a title you’ve already played and it is incorrect. You need to change it once. Wait a few seconds, stop playback, start, wait a few seconds and verify that it remembers your last selection.

**Comment by loeffelpan** [comment]
Nice. I‘m coming over from Plex with PlexKodiConnect because I miss this feature.

Do you mean, that the server remembers the last selection in WebApp? So that is clear and exactly what I want. Kodi should use exactly that audio and subtitle track I selected there. Or would you say that the server remembers what i‘ve chosen last with Emby addon?

PS: Hopefully there are no other features I would miss in Emby when changing from Plex.

**Comment by loeffelpan** [comment]
Thanks a lot.
I will try out.
