### ISSUE TITLE
Smart Playlists broken in Kodi 18

### ISSUE THREAD

**Issue by zalaare** [MediaBrowser/plugin.video.emby#231]
### Describe the bug
I noticed @ LibreELEC v8.95.003 my Smart Playlists stopped working:
- Using the Kodi context menu directly on a playlist and choosing "Play" would lockup kodi for 10s or so then silently do nothing. [NOT PLAY]
- Currently @ LibreELEC v9.0.1 I get "Unable to load playlist".
- Browsing into the same playlist would properly show the video files queued in the playlist.  Selecting one at random and using the Kodi context menu directly on that video choosing "Play from here" would play the video, but fail to play the following.

## Expected Behavior
Obviously, this shouldn't happen.  The playlist should play as expected.

## Possible Fix
I narrowed the problem to a specific commit:
  https://github.com/xbmc/xbmc/commit/4621220312a0fa04cdc5e36e5a0718208908da79
I've patched the commit out of LibreELEC 9.0 and 9.0.1 final release and my playlists work properly again.
I do /not/ have the knowledge to explain why this commit breaks these playlists.

### To Reproduce
1.  Create Smart video Playlist using video sources hosted from an Emby Server.  EXAMPLE:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="episodes">
    <name>Friends</name>
    <match>all</match>
    <rule field="tvshow" operator="is">
        <value>Friends</value>
    </rule>
    <order direction="ascending">random</order>
</smartplaylist>
```
2. Using context menu choose Play on your playlist
3.  NOT Profit

### Kodi Logs
INFO | Kodi 18.1-Leia + Emby Beta addon
(https://zalaare.freeddns.org/logs/20190313-Kodi.Leia-18.1-INFO.Emby.Beta.and.Smart.Playlists.log)
INFO | Patched Kodi 18.1-Leia + Emby Beta addon
(https://zalaare.freeddns.org/logs/20190313-Kodi.Leia.18.1.1-INFO.Emby.Beta.and.Smart.Playlists.log)
DEBUG | Kodi 18.1-Leia + Emby Beta addon
(https://zalaare.freeddns.org/logs/20190313-Kodi.Leia-18.1-DEBUG.Emby.Beta.and.Smart.Playlists.log)
DEBUG | Kodi 18.1-Leia + Emby Stable addon
(https://zalaare.freeddns.org/logs/20190313-Kodi.Leia-18.1-DEBUG.Emby.Stable.and.Smart.Playlists.log)
DEBUG | Patched Kodi 18.1-Leia + Emby Beta addon
(https://zalaare.freeddns.org/logs/20190313-Kodi.Leia-18.1.1-DEBUG.Emby.Beta.and.Smart.Playlists.log)

**Comment by angelblue05** [comment]
Thanks. I'll have a look at your logs.

**Comment by zalaare** [comment]
Couple **Edits** and **Notes**
* I didn't copy-and-paste nicely so some of the logs pointed to nothing, so I fixed that above.
* I wasn't consistent in how I wrote the LOGTYPE | Kodi Ver + Emby ver above, so I fixed that as well. (just some minor OCD)
* I noticed that the "Stable" Emby addon log shows that I'm using the "stable" repo, but still the beta addon, so that log is probably useless as it won't show anything different.  Let me know if you need "stable" emby addon log and i'll use a VM or something to start from scratch.

**Comment by angelblue05** [comment]
Thank you. I will get back to you on this. BTW did this work before? Were you using native playback mode previously when it worked?

I don't think this ever worked with add-on playback. But I'll have to do some more testing. I'll keep you updated as soon as I find out more.

**Comment by angelblue05** [comment]
@zalaare 
Can you try 4.0.12r available via sideload or kodi.emby.media > public testing? Keep me posted if it helps.

**Comment by zalaare** [comment]
I've only ever used add-on playback.
I'll try 4.0.12r tonight when I get home.

**Comment by angelblue05** [comment]
Try 4.0.12x (I've had to fix a few things)

**Comment by zalaare** [comment]
4.0.12x seems to work correctly.  I've attached the log from a clean install/setup w/ 4.0.12x.  Let me know if you need more.

[INFO | Kodi-18.1 Leia + Emby Public Testing v4.0.12x addon](https://zalaare.freeddns.org/logs/20190318-Kodi.Leia-18.1-INFO.Emby.PT-4.0.12x.and.Smart.Playlists.log)

**Comment by angelblue05** [comment]
Thank you, I'll release a new beta tomorrow 4.0.13, it will contain the fix for this.
