### ISSUE TITLE
Ephemeral Port Exhaustion

### ISSUE THREAD

**Issue by jimmielightner** [MediaBrowser/plugin.video.emby#24]
When I initially set up the plugin (on OS X) and run the sync, it throws an error that it can not communicate with the Emby server after some time. If I hop on the Emby server (server 2012 R2) I can see symptoms of ephemeral port exhaustion. Is there a reason the plugin for Kodi would very quickly churn through 16k+ ports during a sync? Please let me know how to gather data to help diagnose this issue. I can capture traces, dumps, etc.

**Comment by angelblue05** [comment]
No, it's not normal. Post your Kodi log (no Kodi debug): http://emby.media/community/index.php?/topic/17599-how-to-report-a-problem/

**Comment by angelblue05** [comment]
If you are still experiencing this issue, feel free to start a thread in our Kodi forums: http://emby.media/community/index.php?/forum/99-kodi/
