### ISSUE TITLE
Separate Transcode 10-bit into H264/H265

### ISSUE THREAD

**Issue by adam111316** [MediaBrowser/plugin.video.emby#255]
In reference to the recent commit c05d1419652828d8aaef950085f53ad96fee093d it looks like H265 10-bit transcoding has been bundled together with H264 transcoding.

Most devices have hardware accelerated Main10 H265 capabilities, but none have High10p H264, therefore transcoding usually is only required for one but not necessarily both. Is it possible to split this into two menu items? e.g.

- Transcode 10-bit (H265/HEVC)
- Transcode 10-bit (H264)

**Comment by angelblue05** [comment]
Ok yes I will do that for the next beta version. Thanks.

**Comment by angelblue05** [comment]
Let me know we are back to normal with 4.0.25a. Thanks!

**Comment by adam111316** [comment]
Worked a charm, cheers!
