### ISSUE TITLE
Playing a iso file (mpeg dvd) error

### ISSUE THREAD

**Issue by mabelisle** [MediaBrowser/plugin.video.emby#26]
Hi, I'm getting this error trying to play some of my old movies that are in a iso format. Kodi can play them natively but it seems that calling the file is creating an exception with the plugin.

`19:44:37 15072.484375 T:1545598016  NOTICE: Using Image Cache Thread Count: 10 -> 1`
`19:44:37 15072.489258 T:1545598016  NOTICE: Parameter string: ?dbid=59&mode=play&id=f4036bcb58b4d6cb6a78442745c0f404&filename=Frozen+%282013%29.iso`
`19:44:37 15072.826172 T:1545598016  NOTICE: Using Image Cache Thread Count: 10 -> 1`
`19:44:37 15072.832031 T:1545598016  NOTICE: EMBY PlaybackUtils -> Play called.`
`19:44:37 15072.857422 T:1545598016  NOTICE: EMBY PlayUtils -> Can't direct play, play from HTTP enabled.`
`19:44:37 15072.867188 T:1545598016  NOTICE: EMBY PlayUtils -> File is transcoding.`
`19:44:37 15072.890625 T:1545598016  NOTICE: EMBY PlaybackUtils -> Setting up properties in playlist.`
`19:44:37 15072.993164 T:1545598016   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.emby.movies/default.py", line 40, in <module>
                                                entrypoint.doPlayback(itemid, dbid)
                                              File "/storage/.kodi/addons/plugin.video.emby/resources/lib/entrypoint.py", line 36, in doPlayback
                                                pbutils.PlaybackUtils(item).play(itemid, dbid)
                                              File "/storage/.kodi/addons/plugin.video.emby/resources/lib/playbackutils.py", line 195, in play
                                                playurl = playutils.audioSubsPref(playurl, listitem)
                                              File "/storage/.kodi/addons/plugin.video.emby/resources/lib/playutils.py", line 423, in audioSubsPref
                                                selectAudioIndex = audioStreamsList[audioStreams[0]]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--`
`19:44:37 15073.205078 T:1967841280   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.emby.movies/?dbid=59&mode=play&id=f4036bcb58b4d6cb6a78$`

I'm using the beta version of the plugin
Thanks

**Comment by angelblue05** [comment]
Yeah, this needs to be fixed, because Emby does not probe iso files anymore.

**Comment by angelblue05** [comment]
Fix will be in the next beta version, whenever that will be. Thanks for your patience :+1:
