### ISSUE TITLE
I don't see the plugin deps on github so I'll post this here.

### ISSUE THREAD

**Issue by SpootDev** [MediaBrowser/plugin.video.emby#28]
In addon.xml in plugin.video.emby.movies it says it's for music videos instead of movies.

**Comment by angelblue05** [comment]
Are you talking about the description?

**Comment by SpootDev** [comment]
Yes.  http://embydata.com/downloads/addons/xbmb3c/kodi-beta-repo/plugin.video.emby.movies/  the xml in this dir and the zip.

**Comment by angelblue05** [comment]
The plugin dependency has been fixed and updated. Thanks
It can now be found here: https://github.com/angelblue05/plugin.video.emby.movies
