### ISSUE TITLE
Merged show folders being split in Kodi interface

### ISSUE THREAD

**Issue by brainfork** [MediaBrowser/plugin.video.emby#286]
I'm getting an issue where shows spread across multiple folders are not staying merged when they're synced into Kodi (18.1), despite being merged as expected in Emby server (4.1.0.26).  This is using the latest version of the plugin (4.1.3)

Split in the Kodi interface:
![Capture](https://user-images.githubusercontent.com/2246606/61265668-3d148f00-a75f-11e9-87c8-2edf7795fb2a.PNG)

Merged in the Emby interface:
![Capture](https://user-images.githubusercontent.com/2246606/61265754-b613e680-a75f-11e9-9558-e1399d5d67fb.PNG)

I've tried repairing the libraries multiple times as well as resetting the local database to no avail.  This is occurring in Kodi on Windows 7 as well as on LibreELEC.  Let me know if I can provide any more detailed information.

**Comment by angelblue05** [comment]
Use the beta server, repair your effected libraries. Or wait for beta to move to stable.

Not all pooling is supported in the stable version with Emby for Kodi. That is resolved with server 4.2.0.23 and higher.

**Comment by angelblue05** [comment]
Beta should move to the Stable channel this week. Let me know if this issue persists. Thank you.

**Comment by brainfork** [comment]
I've switched to EmbyCon, Emby for Kodi is now causing Kodi to crash when trying to sync my library from the server.  Someone else will have to test this.

**Comment by angelblue05** [comment]
Which version were you trying, which server version are you on? Can't say that I see any crashing issue or others have reported anything like that. I have other users with series pooling issue like you reported that say it's resolved already. So I will assume it is already resolved with server 4.2.

**Comment by brainfork** [comment]
Emby for Kodi - 4.1.4
Emby server - 4.1.0.26, Emby .net core from [this](https://forum.libreelec.tv/thread/12604-net-core-runtime-and-emby/) Kodi addon
Running on Raspberry Pi 3 as well as Windows 7; server is on the RPi Kodi is on both.
