### ISSUE TITLE
Installation of Emby server

### ISSUE THREAD

**Issue by David-Lor** [MediaBrowser/plugin.video.emby#288]
On the [Wiki](https://github.com/MediaBrowser/plugin.video.emby/wiki) I cannot find anything about How to install the Emby server, the one Kodi & its Emby client will connect to. Only install points are Install Emby for Kodi, Install Kodi companion, Install Embuary skin by Sualfred.

**Comment by LukePulverenti** [comment]
Hi there, Emby server install instructions can be found on our website:
https://emby.media/download.html

Although it's probably not a bad idea to link to it from that wiki. Thanks.

**Comment by angelblue05** [comment]
Added the link within the steps. The server link is already at the top of every wiki pages.
