### ISSUE TITLE
Invalid setting of artist in itemtypes.py

### ISSUE THREAD

**Issue by SpootDev** [MediaBrowser/plugin.video.emby#29]
In itemtypes.py at line 847 the following code:
# Process cast
        people = item['People']
        artists = item['ArtistItems']
        for artist in artists:
            artist['Type'] = "Artist"
        people.extend(artists)

Either 851 should be artists[ or for loop can be removed as artist is never used in function.

**Comment by faush01** [comment]
it looks like they are adding the 'type' to the artists list before adding it to people.
is that not correct?

**Comment by SpootDev** [comment]
Then it's missing the s.

**Comment by faush01** [comment]
Please re write the code block above with the missing s so I can see what you mean

**Comment by angelblue05** [comment]
What are you talking about. This is part of the verification done in kodidb_functions - adding people.

**Comment by angelblue05** [comment]
kodidb_functions - line 288 and 423. :)

**Comment by angelblue05** [comment]
I'm going to assume this is not an issue, from the lack of response, hehe.

**Comment by SpootDev** [comment]
Ha, sorry......been busy with my fork.  :)
