### ISSUE TITLE
Artwork Cache Issue

### ISSUE THREAD

**Issue by weebl101** [MediaBrowser/plugin.video.emby#298]
hi @angelblue05 just wondering ifyou could help identify why my cache wont work. I am getting an error message. Log is attached

https://drive.google.com/open?id=1WeveKaJ5oI9OcHI3lgrgPZWGaCMXzr8G

Thanks again for your help

**Comment by angelblue05** [comment]
I'm looking into it. Thanks for taking the time to report this issue.

**Comment by angelblue05** [comment]
Restart Emby for Kodi or Kodi. A new patch will be applied to fix this. It should work now.

**Comment by weebl101** [comment]
All fixed. Thank you
