### ISSUE TITLE
add own PictureViewer dialog for homevideo&photos via video node

### ISSUE THREAD

**Issue by sualfred** [MediaBrowser/plugin.video.emby#301]
Pictures don't open by accessing them thru MyVideoNav.xml but from MyPictures.xml
Bzt homevideos doesn't honor resume states from the pictures path.
So there is no rule to fit both scenarios.

Solution:
Adding everything to the video path and use a custom PictureViewer dialog approach. 
EmbyCon does this.

2 ways:
- Using thte webservice that is calling it
- Use a own plugin path entrypoint 

Take a look at EmbyCon for reference

**Comment by angelblue05** [comment]
Added with 4.1.17
