### ISSUE TITLE
Playback fails frequently with Emby for Kodi

### ISSUE THREAD

**Issue by chjohans** [MediaBrowser/plugin.video.emby#312]
This happens frequently after upgrading to Kodi 18 Leia, the same never happened with Kodi 17.

Since upgrading to Kodi 18 Leia playback fails way too frequently in Kodi with the message "One or more items failed to play. Check the log for more information about this message.". It also takes a while (typically 20-40 seconds) before this message appears. Usually it will actually start playing the stream exactly when this message is being shown, and of course the stream stops playing as soon as I click OK to get rid of the message. So the stream actually starts to play about 9 times out of 10 this message is shown, when it's not the message will just show without the stream playing. This happens with all my movies/TV series, and seems not to be related to the file format or codec.

When this happens every subsequent play attempt will fail the same way, the fix seems to be to restart Kodi. Extremely annoying since Kodi takes a while to restart because of my massive list of Live TV channels. It happens almost daily so it's most annoying. After a restart the same error will usually appear again after having played 1-3 titles in Kodi.

There are at least two threads describing the same bug in the Community forum over at emby.media, and it seems to affect quite a lot of users. Hopefully the reason for this most annoying and frequent error can be found and fixed.

**Comment by angelblue05** [comment]
This should be resolved with 4.1.15, report back if otherwise, thank you.
