### ISSUE TITLE
default settings suggestions

### ISSUE THREAD

**Issue by horstepipe** [MediaBrowser/plugin.video.emby#313]
please share your experiences about paging values. I'm getting best/fastest syncs on all devices (low-powered, high-powered) with these:
`max items requested: 50`
`download threads: 1`

It doesn't seem to make a difference whether "max items" is set to 50 or 500, guess the server sets a limit here...?

Another suggestion:
Keep "Enable cinema mode" enabled by default, but also enable "Ask to play trailers". Surprising many of my people were very confused when I initially enabled Cinema Mode serverside. I got questions like 

> Something's completely going wrong. The movie doesn't start anymore, instead something starts in English which looks like a trailer.

I really had to laugh lol

**Comment by angelblue05** [comment]
To answer your question about max items, it does make a difference when gathering items in bulk. The smaller the number, the more calls it will have to make to your server to grab the entire list of items the add-on is trying to get.

For the trailer, I don't think I will change the default for the simple reason that Emby doesn't do this and that would force users to go into settings to disable what could be perceived as an annoyance.
