### ISSUE TITLE
season names are not being changed in Kodi

### ISSUE THREAD

**Issue by horstepipe** [MediaBrowser/plugin.video.emby#314]
Season name changes in Emby Server are not being applied in Kodi when Kodi was not running while you changed the season name.

Steps to reproduce:

- Stop Kodi
- Change a season name in Emby Server
- Start Kodi

The change seems to be recognized by Kodi (log line 1879)
[seasonnames.log](https://github.com/MediaBrowser/plugin.video.emby/files/3808506/seasonnames.log)

**Comment by angelblue05** [comment]
Fixed with 4.1.15
