### ISSUE TITLE
Library scan fails when media item is missing

### ISSUE THREAD

**Issue by horstepipe** [MediaBrowser/plugin.video.emby#315]
absolutely no priority, but for the sake of completeness I'll write it up here:
If you remove a media item which is part of an Emby library and don't do a library scan in Emby Server afterwards and the real time monitor is disabled, syncing that library fails in Emby for Kodi.

Steps to reproduce:
- Disable real time monitoring for that library in Emby Server
- Remove an episode/movie from your storage/hdd which is part of that library
- Don't do a library scan in Emby Server
- Try to sync that library in Emby for Kodi

Maybe it's possible to add a better exception handling here some day.
[add_library_missing_item.log](https://github.com/MediaBrowser/plugin.video.emby/files/3808582/add_library_missing_item.log)

**Comment by angelblue05** [comment]
This should be resolved with 4.1.19.
