### ISSUE TITLE
cosmetic: percentage value doesn't increase on "processing updates"

### ISSUE THREAD

**Issue by horstepipe** [MediaBrowser/plugin.video.emby#316]
Again, just for the sake of completeness:
The percentage value of the sync which shows up after Kodi start doesn't increase. It stays at 0%.

![screenshot002](https://user-images.githubusercontent.com/10515479/68280704-5b87f880-0076-11ea-8ded-687eb8ce281c.png)

**Comment by angelblue05** [comment]
Fixed with 4.1.17
