### ISSUE TITLE
Add support for audiobook library

### ISSUE THREAD

**Issue by payback007** [MediaBrowser/plugin.video.emby#329]
Dear all,

I'm new to emby and currently setting up emby with kodi. Kodi is used for LiveTV and emby is bringing video, music, musicvideos and series database to kodi. But I'm missing support for audiobooks library. Is it possible to add also audiobook library to use it with kodi?

Thank's very much for the current addon, it's doing a great job!

**Comment by angelblue05** [comment]
Thank you. It's definitely on my todo list. I don't have a timeframe for it yet.

**Comment by quickmic** [comment]
Also on my todo list. I've to check Kodi's capabilities for audiobooks

**Comment by quickmic** [comment]
Done in 6.x
