### ISSUE TITLE
Up Next Addon 

### ISSUE THREAD

**Issue by weebl101** [MediaBrowser/plugin.video.emby#332]
Hi @angelblue05 the up next function doesn’t seem to be working as intended. 

If you select play now when the dialog box comes up from the first played episode, it will play one or two episodes automatically after the next episode in the playlist, however, if you don’t select the play now button on the dialog box, it will send you back to the episode screen after the first played episode has completed. 

I can upload a log tomorrow. I hope the above makes sense. 

Thanks again.

**Comment by weebl101** [comment]
hi @angelblue05 here is a copy of the kodi log I hope it helps https://drive.google.com/file/d/1UEydRb6xbTAQLath6CBSBNgA6fjZuxz0/view?usp=sharing

**Comment by angelblue05** [comment]
Thanks, will look into it.

**Comment by quickmic** [comment]
Will be fixed/replaced in 5.X  with stock Kodi functionality)

**Comment by quickmic** [comment]
Fixed in 5.x
