### ISSUE TITLE
Watched status with External Player 

### ISSUE THREAD

**Issue by Ashyni** [MediaBrowser/plugin.video.emby#335]
Hello,

I'm using MPC-BE with Kodi, after playing something, it's marked as watched then unmarked shortly after, like emby is syncing back the status because he think the time played is to short, we need a workaround for external player.
Manually mark as watched is working but annoying.
Changing the min/max resume % value to 0 is working but not a proper workaround for other regular user (internal player).

Kodi: 18.5
Emby-for-kodi: 4.1.19
Kodi-Companion: 2.1.4
Emby: 4.3.1.0

Logs: 
https://pastebin.fr/60148
if you need emby server log, let me know.

Happy New Year !!

**Comment by quickmic** [comment]
Is this still an issue? Please migrate to emby-for-kodi-next-gen
