### ISSUE TITLE
HTTP/2 Support

### ISSUE THREAD

**Issue by darthShadow** [MediaBrowser/plugin.video.emby#336]
Using Hyper along with its Requests integration should result in a minimal change in code. Reference: https://hyper.readthedocs.io/en/latest/quickstart.html#requests-integration

**Comment by quickmic** [comment]
I'll give it a try.

**Comment by quickmic** [comment]
I've checked hyper. Unfortunately, it not a native python function. This means, not available on multiple devices so I cannot add this feature.

**Comment by darthShadow** [comment]
Oh, ok. Thanks for checking.

Any info about which platforms are not supported since I couldn't find anything regarding that from a brief search.

**Comment by quickmic** [comment]
Well, Kodi uses its own python interpreter. Hyper must be installed e.g. via pip/pip3.
So almost every box which doesn't allow external python libs are not supported. e.g. Android.
Also hyper is based on additional python libs which are also not python native.
I could be possible, if you trace back all dependencies of hyper and add them manually to the plugin, but a hell of effort with no guarantee if it works.
If all the dependencies of hyper are python (only) code, it could work. If only one dependency uses C code, you need compiled version for each platform.
I hope, requests will add http/2 some day.

**Comment by darthShadow** [comment]
It should be includable in the plugin if you want to.

---

Hyper is specifically advertised as a pure-python library so there should be no C code. I traced its dependencies from its [setup.py](https://github.com/python-hyper/hyper-h2/blob/master/setup.py) and there are only 2:

* [hyperframe](https://github.com/python-hyper/hyperframe/blob/master/setup.py) - Pure python & no dependencies
* [hpack](https://github.com/python-hyper/hpack/blob/master/setup.py) - Pure python & no dependencies

**Comment by quickmic** [comment]
correct:
root@workstation2:/home/quickmic# pip3 install hyper
Collecting hyper
  Downloading hyper-0.7.0-py2.py3-none-any.whl (269 kB)
     |████████████████████████████████| 269 kB 6.2 MB/s 
Collecting h2<3.0,>=2.4
  Downloading h2-2.6.2-py2.py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 568 kB/s 
Collecting hyperframe<4.0,>=3.2
  Downloading hyperframe-3.2.0-py2.py3-none-any.whl (13 kB)
Collecting hpack<4,>=2.2
  Downloading hpack-3.0.0-py2.py3-none-any.whl (38 kB)
Installing collected packages: hpack, hyperframe, h2, hyper
Successfully installed h2-2.6.2 hpack-3.0.0 hyper-0.7.0 hyperframe-3.2.0

**Comment by darthShadow** [comment]
So, still on the table for consideration then?

**Comment by darthShadow** [comment]
Btw, it's [h2](https://pypi.org/project/h2/) now. Looks like [hyper](https://pypi.org/project/hyper/) was renamed.

**Comment by quickmic** [comment]
Yes, but no priority. If I add hyper "manually", I've to support and maintenance versioning.
e4k plugin (5.x) uses "requests" also from kodi repo. No longer added via plugin code for exactly the same reason.

But let's see, what I can do. Probably I'll drop "requests" and use native python libs. imho would be the best option. Actually I'm not a big fan of addons (like requests) in general. Usually they have a performance impact due to overhead.

**Comment by darthShadow** [comment]
That's perfectly fine. There is no urgency to this. I just wanted to have it on the roadmap for if & when you have the free time.

**Comment by quickmic** [comment]
update:
2.0 is supported by Kodi stream queries, but not while sync. There are still limitations
