### ISSUE TITLE
Movie playback has issues when cinema mode is enabled

### ISSUE THREAD

**Issue by godfuture** [MediaBrowser/plugin.video.emby#337]
I have disabled cinema mode because the playback of my media had issues. When I started a movie, some random file from Emby server was played. Sometimes a music file, other times a movie or video. I don't know if by definition this is expected to happen with cinema mode enabled. For example instead of the video stream I saw the audio player background of Kodi. The movie was played audio only. It seems there are sometimes issues to switch from the cinema mode media to the intially played one.

**Comment by quickmic** [comment]
Please try with 5.x version

**Comment by MRiggs100** [comment]
@quickmic I use the latest yesterday, and if the "people" is checked you can't playback almost nothing. With this unchecked, work fine.

**Comment by quickmic** [comment]
I'll put it on the list. Thanks for reporting

**Comment by quickmic** [comment]
I think it should be solved in 6.x beta. Let me know, if you still experience issues.

**Comment by MRiggs100** [comment]
Hi!
I did the report to you in Emby forum. Is fine after one week of my report here. Thanks!

**Comment by quickmic** [comment]
Thanks
