### ISSUE TITLE
Option to remove menu items.

### ISSUE THREAD

**Issue by fusk-l** [MediaBrowser/plugin.video.emby#338]
Needs an option to disable changelog, add server, add user, manage libraries, sets, By first letter etc. When starting plugin, i only want to see two menu items, movies and tv. If i enter either one i only want to see maybe two options. The rest is just clutter.

**Comment by quickmic** [comment]
I assume it's possible, is there a specific reason for that feature?

**Comment by quickmic** [comment]
no response
