### ISSUE TITLE
Episode Thumbnails

### ISSUE THREAD

**Issue by weebl101** [MediaBrowser/plugin.video.emby#339]
Hello,

I am having an issue with episode thumbnails disappearing after the episode is marked as watched. I am using Arctic Zephyr 2 skin. Kodi log attached. I have added two just in case, one is older one is newer.

https://drive.google.com/open?id=1WeveKaJ5oI9OcHI3lgrgPZWGaCMXzr8G

https://drive.google.com/open?id=1Xf8r6cwEuz2qiLZx_3V58jJSyelcLQVQ

**Comment by weebl101** [comment]
Hi @angelblue05 I was just wondering if you were able to help with the above. For some reason the episode thumb is being deleted when the item is being marked as watched.

2020-03-29 00:26:38.098 T:13672  NOTICE: EMBY.objects.kodi.artwork -> DELETE cached d/ddf6cfa3.jpg

**Comment by quickmic** [comment]
Will be fixed in 5.X version

**Comment by quickmic** [comment]
Fixed in 5.x
