### ISSUE TITLE
Can't change font size

### ISSUE THREAD

**Issue by RafaelLinux** [MediaBrowser/plugin.video.emby#340]
I was really mad looking for how to change font size, but maybe it's a feature not implemented, so I can't just use Emby. 
Please, will you implement this feature?

Thank you

**Comment by quickmic** [comment]
Are you talkin about emby for kodi plugin or emby (server)?

**Comment by RafaelLinux** [comment]
I'm sorry, too much months to remember. Even I think I was talking about Embuary Kodi SKIN, so this thread can be closed.

**Comment by quickmic** [comment]
not related to emby for kodi
