### ISSUE TITLE
Server login screen: Host is not actually the host

### ISSUE THREAD

**Issue by anoma** [MediaBrowser/plugin.video.emby#342]
Currently the popup that allows you to set the location of the Emby server asks for two bits of information, host and port.

However the data required in the host field is not actually the hostname it its the URL and requires HTTP or HTTPS set correctly.

Suggest a third boolean SSL/TLS field is added to compliment the existing host and port fields.

Example current:

Host: https://emby.example.com
Port: 443

Example new:

Host: emby.example.com
SSL/TLS: On
Port: 443

**Comment by quickmic** [comment]
I will add that

**Comment by quickmic** [comment]
sorry, I have to keep the current approach due to compatibility.
