### ISSUE TITLE
Allow for smaller reset/syncs

### ISSUE THREAD

**Issue by nomandera** [MediaBrowser/plugin.video.emby#353]
With enough churn over time Emby and Kodi can go subtly out of sync. It isnt radical and I cant find the root cause although I strongly suspect it is sometimes triggered when a TV show has new and deleted episodes in one sync cycle. Once this happens the only current fix is a complete new clean sync of all content. This is slow.

It seems sensible regardless to allow for smaller reset/syncs to help in scenarios like this and as a general "quality of life" feature. e.g. reset and resync just this episode/season/show/move

**Comment by quickmic** [comment]
Hi

I know there was a bug in TV-Shows sync code that exactly matches your issue discription:
https://emby.media/community/index.php?/topic/90223-e4k-tv-show-sync-corner-case/

I've fixed that in 4.1.21
Are you using this version (available in emby for kodi beta repo) or here on github.
Possibly you have to rebuild the (TV-show) DB after upgrade to 4.1.21.
If you are already using this version, do you still experience issues with 4.1.21?

Acutally I wanna fix the core bug and not write workaround.

**Comment by anoma** [comment]
Let me test and get back to you. I cannot generate this error on demand but I can recognize it when I see it

**Comment by anoma** [comment]
OK I have just hit the issue with 4.1.21 which I assume is an auto update from a manual install many moons ago as it shows up as having no repository. Happy to install from better source if needed.

What I cant conform yet is if I have reset the dbase since this version. It is never more than a few weeks since I have done a reset as it constantly hits this issue but to be sure I will have to do it again now. This takes a very long time and I need a day when no family needs the device to do it.

**Comment by quickmic** [comment]
Yes please, rebuild/wipe the DB first. 
As a hint, I perform full syncs on a PC and copy DB (and some settings) to the low powered devices. It's much faster

**Comment by anoma** [comment]
Without wishing to go to far off topic how close to Kodi and Emby addon versions need to match using this kind of sync?

Is it enough for the Emby addon and Kodi back end dbase version to be same version (i.e. the kodi dbase version is same for entire major release cycle and serveral versions of kodi)

**Comment by anoma** [comment]
Just to update progress.

It would appears all my physical and virtual, test and real, beta repo add installs broke for unknown reasons some time in the past and stuck me on 4.1.21. I have activated them all again and they all immediately updated to 4.1.22.

I have one profile that has been rebuilt after 4.1.21 and again after 4.1.22. I continue to try to "inspire" the bug to raise its head but I have not achieved this yet which is a good sign that it may be fixed. I will keep testing as the only real way to know for sure is churn and the passage of time.

**Comment by anoma** [comment]
I have just hit my first confirmed sighting of this bug again using 4.1.22.

Whilst tidying up i went from:

/show/
/show/mixed.s02.eps
/show/season2folder/mixed.s02.eps

via this

/show/
/show/season2folder_recorded/mixed.s02.eps
/show/season2folder_ripped/mixed.s02.eps

and then finally to this

/show/show/season2folder_ripped/mixed.s02.eps

within a short period of time.

In Emby all is fine but in Kodi the show is completely gone.

**Comment by quickmic** [comment]
Can you please try with 5.1.3? I fixed a major sync bug in this version.
Available in emby-kodi beta repo called "emby-next-gen"

**Comment by anoma** [comment]
Sorry I missed the reply. Yes I will test this ASAP.

**Comment by quickmic** [comment]
In latest 6.x beta, sync is massive improved. Let me know, if there are still issues.
