### ISSUE TITLE
Local Server on LibreELEC

### ISSUE THREAD

**Issue by gioluca2** [MediaBrowser/plugin.video.emby#355]
Hi, I have libreelec 9 on my Wetek Openelec (aka Wetek Play 1) box.
Could I install emby server on this box and use this addon to manage itself?

Thanks

**Comment by LukePulverenti** [comment]
Hi, a community member is currently packaging Emby Server for libreelec so yes you can install it. However if you can run Docker, then I would suggest installing Emby Server with that as it is packaged by us officially.

**Comment by anoma** [comment]
At the time this was a brilliant device for the money but you should probably set your expectations quite low that a 5 year old $90 SoC box can be performant as a simultaneous media player  and a Emby server. e.g I replaced mine 3 years ago for a $40 AML device for a big boost in perforce.

**Comment by CHBMB** [comment]
> At the time this was a brilliant device for the money but you should probably set your expectations quite low that a 5 year old $90 SoC box can be performant as a simultaneous media player and a Emby server. e.g I replaced mine 3 years ago for a $40 AML device for a big boost in perforce.

I agree fwiw, I've since moved from AML to a Pi4 based system as well.

**Comment by gioluca2** [comment]
> Hi, a community member is currently packaging Emby Server for libreelec so yes you can install it. However if you can run Docker, then I would suggest installing Emby Server with that as it is packaged by us officially.

Could you link me the guide to install it with docker? Sorry but I never did that before. 

> At the time this was a brilliant device for the money but you should probably set your expectations quite low that a 5 year old $90 SoC box can be performant as a simultaneous media player  and a Emby server. e.g I replaced mine 3 years ago for a $40 AML device for a big boost in perforce. 

I know that. Do you think I can use them differently (server accessed only when not using the box like media player) or it's too old regardless of that (two services can't be used)?
Alternatively I can install emby server on the nas thecus n2310 or zyxel 325v2. Which one is better than my box?

**Comment by CvH** [comment]
> Could you link me the guide to install it with docker?

there is no docker for for the WP1, bottom line - too old and no Linux support (besides the super old stuff that was pushed at release date). The kernel dates to mid 2013 :)

**Comment by gioluca2** [comment]
> > Could you link me the guide to install it with docker?
> 
> there is no docker for for the WP1, bottom line - too old and no Linux support (besides the super old stuff that was pushed at release date). The kernel dates to mid 2013 :)

What do you think about NAS Thecus N2310 or Zyxel 325v2?

**Comment by LukePulverenti** [comment]
Our Docker instructions can be found here: https://emby.media/download
Please note you'll need to install Docker itself first on libreelec

**Comment by gioluca2** [comment]
Do you think it will work on my wetek openelec? @CvH says no.

**Comment by anoma** [comment]
You have teamsters from LibreELEC, Emby and LinuxServer.io here so your confidence can be high that the advice is correct.

Other than the facts you own the WP1 and that it can act as a tuner it is EOL and not special any more. You should if at all possible replace it or restrict yourself you technology of the period to run on it.

If you need it to perform as a tuner you can turn it into a minisatip client.

**Comment by gioluca2** [comment]
What about my two NAS?

**Comment by CvH** [comment]
@gioluca2 that are two old low end NAS systems, so very likely the answer is no. Better get an RPi4 or something.

**Comment by quickmic** [comment]
closed due to inactivity
