### ISSUE TITLE
Kodi 19 Matrix Support

### ISSUE THREAD

**Issue by bernhardberger** [MediaBrowser/plugin.video.emby#357]
Hi, since the Matrix Beta update just got forced on me by my Shield... are there any plans to support Kodi 19?

**Comment by quickmic** [comment]
Yes, but will take a few weeks.

**Comment by CvH** [comment]
K19 final is likely due early January 2021

**Comment by bernhardberger** [comment]
> Yes, but will take a few weeks.

Thank you. 

Just wanted to make sure there are plans going forward or if I need to switch to that Jellyfish thingy. Read somewhere in the Emby forums that Matrix support probably wasn't coming, so wanted to make sure before prematurely canceling any payments..

Will eagerly await Matrix support as my install is doomed now thanks to stupid Android beta auto update with now downgrade path..

**Comment by quickmic** [comment]
Matrix support is given by emby-next-gen plugin. Now available in emby beta repo
