### ISSUE TITLE
Emby addon incompatible with / not available for Kodi 19 Matrix

### ISSUE THREAD

**Issue by chessplayer60** [MediaBrowser/plugin.video.emby#359]
Hi there, on my Android TVs, Kodi just upgraded to 19.0 Matrix and unfortunately the Emby addon became non functional. It seems like by adding the latest beta-repo, Emby-next-gen does the job, but still I would like to ask what the plans are for a stable release of the Kodi Emby (next-gen?) addon? Currently, the main repo only contains EmbyCon, which I was explicitly discouraged from when I started using Emby for Kodi quite some time ago.

And, before I forget, thanks for the awesome addon it has wokred like a charm for quite some time now!

EDIT: Unfortunately, the Emby-next-gen addon seems to have trouble actually playing the titles - the database was built up again. So, really desperately waiting for the addon in a compatible fashion ...

**Comment by MRiggs100** [comment]
Yesterday it works fine to me, do a clean installation and then pull the latest next-gen version of Emby from the public folder. Wait until is installed. then log in your server with your credentials and that's it. you need to add the repo: https://kodi.emby.media/

**Comment by chessplayer60** [comment]
Well, that is what I did and it did not work for me, unfortunately. However, after installing 18.9 again, it briefly worked, but then did not. So there seems to be some problem I do not know about (while it still works on my FireTV Stick ...). I guess, I will sort it out at some point ...

**Comment by chessplayer60** [comment]
I will close this issue, since it seems this was actually my fault (it has been a while since I needed to install something new here, so I messed up regarding native paths vs. addon standard playback). There is a new issue I might raise after some more testing, though, but that seems to be an issue on the server side.
