### ISSUE TITLE
[Noob question] Android installation

### ISSUE THREAD

**Issue by Saya47** [MediaBrowser/plugin.video.emby#360]
Hello
I added https://kodi.emby.tv:443/ repo and installed embyCon and emby addons just fine on my laptop.
I also added the repo on my Android and installed embyCon but emby (plugin.video.emby) doesn't show up on the list. I tried downloading the zip from here and install the zip on my Android device but it says : `xmbc.python.version could not be satisfied`
Tried installing the files from the repo in the Dependencies folder, that also didn't work.
I take it's not supported on Android? Or am I missing something?
Thanks in advance!

**Comment by Saya47** [comment]
Also, I can not find Kodi companion in any category. I found the `Install Embuary skin by Sualfred (recommended)` in the Look and Feel category, but Kodi companion is no where to be found.

**Comment by MRiggs100** [comment]
The repo is https://kodi.emby.media/
look into public folder and install the latest emby-next-gen version
Do a fresh install of Kodi.

**Comment by Saya47** [comment]
Thanks very much!
