### ISSUE TITLE
Change MPAA format for UK

### ISSUE THREAD

**Issue by maforshaw** [MediaBrowser/plugin.video.emby#368]
Emby stores UK movie certificates in the format "GB-12", "GB-15" etc.

However, most Kodi skins (I've checked three) expect the mpaa field to be "UK:12", "UK:15" etc.

This is easily fixed inside function "get_mpaa" of "helper/api.py" as follows:

```python
       if "GB-" in mpaa:
            mpaa = mpaa.replace("GB-", "UK:")
```

I've tested the change and skins now show the correct certificate flag. Please would you add this change to emby-next-gen. Thanks.

**Comment by quickmic** [comment]
thanks for reporting. I fix it in next beta.
