### ISSUE TITLE
Can we get support for generating  .strm like google drive addon ? 

### ISSUE THREAD

**Issue by alazabe** [MediaBrowser/plugin.video.emby#380]
Hi 
Can you support generating .strm files ? Just like google drive addon , that will amazing to add the artworks for kodi and trailes and mange subtitles with kodi media tools like media elech ,ember and tiny media manger 
And netflix and amazon addon will work with it problems

**Comment by quickmic** [comment]
Please try latest version:

**Comment by quickmic** [comment]
As discussed in forum, not on the agenda.
