### ISSUE TITLE
timestamp out of range errors when nfo files contain YEAR tags in the future

### ISSUE THREAD

**Issue by m4tt075** [MediaBrowser/plugin.video.emby#393]
**BACKGROUND** 
The nfo files of some home videos contained wrong metadata with year tags in the future (>= 2038)

**OBSERVED BEHAVIOR**
Scraping the emby library containing them threw an exception `timestamp out of range for platform time_t` and aborted the scraping process

**WORKAROUND**
Correcting the wrong metadata fixed the scraping issues. Still...

**EXPECTED BEHAVIOR**
Scrape the wrong year tags or handle the exception

**LOG FILE** 
http://ix.io/3DDs

**SYSTEM:**
- CoreElec 19.3 / Kodi 19.3
- Emby server: 4.6.4.0
- Emby NG Addon: 6.1.5

**Comment by quickmic** [comment]
I'll add a year-check, thanks for reporting.

**Comment by quickmic** [comment]
I think it's fix in latest beta.
