### ISSUE TITLE
Can't connect to repository

### ISSUE THREAD

**Issue by kasper1705** [MediaBrowser/plugin.video.emby#40]
There seems to be a problem with the connection to the server for installing Emby for Kodi from the repository. It only comes with the message "Could not connect to the repository. The problem occurs both with the stable and beta repository

**Comment by kasper1705** [comment]
I might add that it is possible to get to the homepage http://kodi.emby.media, Kodi is installed on a Win 10 machine and I have checked for firewall restrictions

**Comment by angelblue05** [comment]
Enable Kodi debug, try to install the add-on, then post your log.

**Comment by kasper1705** [comment]
It seems to work now miraculously. Will post a Kodi debug if it occurs again

**Comment by angelblue05** [comment]
Hehe, nothing changed on our side. Great to hear it's working now.
