### ISSUE TITLE
Offer delete after playback - setting does not work

### ISSUE THREAD

**Issue by silv3r23** [MediaBrowser/plugin.video.emby#421]
Since a few month I notice a misbehavior using the "Offer delete after playback" setting. 
I enabled it for movies only, what works. It is disabled for episodes but it asks me after I ended watching an episode to deleting it too.
Its very annoying. Please fix it. 
I Use the latest addon (v6.2.14) from emby repository for Kodi (19.3)

**Comment by quickmic** [comment]
I'll check that. Have you enabled autoplay next episode in Kodi player settings?

**Comment by quickmic** [comment]
should be fixed by 6.2.16

**Comment by silv3r23** [comment]
> I'll check that. Have you enabled autoplay next episode in Kodi player settings?

sorry for my late reply, no i havent it enabled
