### ISSUE TITLE
Play Using - Missing from EmbyCon Videos but External Players work

### ISSUE THREAD

**Issue by FreeSoftwareServers** [MediaBrowser/plugin.video.emby#436]
I currently have Kodi setup to use the Kodi player by default, but I like to have VLC as an option for External Player.

I've set it up correctly and realized it's only missing option when I navigate to videos using Embycon add-in.

IE:

If I navigate via files to a video I can use "Play Using" --> "VLC"

![image](https://user-images.githubusercontent.com/16218200/190928400-0bd7c4cd-0bd7-4c0e-9c15-a82dcf8263cf.png)

![image](https://user-images.githubusercontent.com/16218200/190928367-1d249410-293b-465b-bd2f-9002886873de.png)

But if I go via Embycon it's not an option (I've scrolled thru options FYI as this is a scroll menu) -->

![image](https://user-images.githubusercontent.com/16218200/190928446-eb502079-d987-434e-8044-3acb31a63d04.png)

Interestingly, if I use `playcorefactory.xml` to set a RULE to use `VLC` vs an "option" by just having under `players` not only does it work, but Emby can track "view time" currently in VLC.

```
<?xml version="1.0" encoding="UTF-8"?>
<!--
# Goes inside %APPDATA%\kodi\userdata
# https://www.freesoftwareservers.com/display/FREES/Kodi+-+Make+Kodi+Use+External+Player+MPC+or+VLC+x64
-->
<playercorefactory>
<players>
<player name="VLC" type="ExternalPlayer" audio="false" video="true">
<filename>C:\Program Files\VideoLAN\VLC\vlc.exe</filename>
<args>"{1}" --no-embedded-video --fullscreen --play-and-exit</args>
<hidexbmc>false</hidexbmc>
<hideconsole>false</hideconsole>
<warpcursor>none</warpcursor>
</player>
<player name="Media Player Classic" type="ExternalPlayer" audio="false" video="true">
<filename>C:\Program Files\MPC-HC\mpc-hc64.exe</filename>
<args>"{1}" /fullscreen /close</args>
<hidexbmc>false</hidexbmc>
<hideconsole>false</hideconsole>
<warpcursor>none</warpcursor>
</player>
</players>

<rules action="prepend">

   <rule filetypes="avi|mkv|mp4|m4v|mpg|mpeg" player="VLC" />
   <!--
   <rule filetypes="avi|mkv|mp4|m4v|mpg|mpeg" player="Media Player Classic" />
-->
</rules>
```
</playercorefactory>

**Issue:**
* No "Play Using" option when viewing files via Embycon

**Expected Behavior:**
* Show "Play Using" option (perhaps only when 'Direct Play' is available?)

**Issue:**
* When playing video stream via VLC Emby can see that user is watching Video and Track Playtime, but when closing stream, it is not added to "in progress" but marked as watched.

**Expected Behavior:**
* Mark Video as Partially Watched in Emby/Kodi when exiting stream

Below is a screenshot of using both VLC and Kodi built in player and looking at Emby WebUI. The currently playing video is using VLC as seen in taskbar at bootm.

![image](https://user-images.githubusercontent.com/16218200/190928690-4ae6021e-b0a3-46f9-adc3-e374a448c7e3.png)

**Comment by quickmic** [comment]
Sounds like you are reporting an EmbyCon issue, right? Actually this is the git for a different plugin. Emby for kodi (next gen).
I leave it opened and dropped a link in the support forum:
https://emby.media/community/index.php?/topic/112544-external-player-issue/

**Comment by faush01** [comment]
I will comment here and on the forum.

EmbyCon is not designed to work with external players and can not correctly report duration and current play position with external players.
What you see above where it looks like it is tracking the time it is not, Emby server does this to smooth out the 10 second update windows that clients use to send updates back to the server, it will count to 10 and then reset back to 0

**Comment by quickmic** [comment]
I close this issue due to no response.
