### ISSUE TITLE
Reloading skin makes for a bad impression on Kodi startup

### ISSUE THREAD

**Issue by Saviq** [MediaBrowser/plugin.video.emby#438]
Since https://github.com/MediaBrowser/plugin.video.emby/commit/fac19e84aaae14f8a798665212d038848e5f561c the addon reloads the Kodi skin after the first sync. It makes for a very annoying jump in the UI when you've already gone down some media tree and you get thrown back, somewhat randomly depending on where you were.

I use profiles to switch between family members and this is triggered on every profile switch, which makes it all the more annoying. Can you comment if it's possible to disable this behaviour? I didn't see any issues prior to this getting introduced.

**Comment by quickmic** [comment]
Yes it is possible to disable skin refresh
for 7.x:
plugin-config menu -> interface -> refresh skin on Emby server connection.

**Comment by quickmic** [comment]
option is available in plugin config menu
