### ISSUE TITLE
Multi versions: Version selection not showing up anymore

### ISSUE THREAD

**Issue by Noustaa** [MediaBrowser/plugin.video.emby#441]
Hi, i was with version 7.9.2 and it was working fine with same addon settings (native mode), if a movie has more than 1 version, when i play it it shows version selection screen. 
Just updated to 7.9.4 and now it is playing straight any of the versions without showing the selection screen.

I tested both native and the other mode (forgot its name), only native has this issue.
Don't know if anyone else has the same issue

**Comment by quickmic** [comment]
Thanks, I'll review the issue.

**Comment by Noustaa** [comment]
Hey, just FYI, i just have tested 7.10.0 and the issue is still the same

**Comment by quickmic** [comment]
I also performed a test with movies and tvshows multiselection, works perfect on my setup. Must be something specific to your setup. Without further information impossible to debug.
Do you have an account in the support forum?

https://emby.media/community/index.php?/topic/106853-embyforkodi-next-gen-7xx-support/

Unfortunately I need you data for review. You can send it via PM in the forum. I need your:
.kodi/userdata/Database/MyVideos119.db
.kodi/userdata/Database/emby_YOURSERVERIDHERE.db
.kodi/userdata/addon_data/plugin.video.emby-next-gen/settings.xml

...no worries, they doesn't include any confidential data.

**Comment by Noustaa** [comment]
Hey, sorry im currently away from home. I forgot to precise that i do have only STRM files on my emby server. Would it be possible for you to try with same configuration ? 
Otherwise, i'll upload logs when i get back home in some days.
And in you first test, did you try with native mode ? Not addon mode.
Because addon mode works fine for me.

**Comment by quickmic** [comment]
Yes I tested in native mode. I'll try strm files, maybe I can reproduce the issue.

**Comment by quickmic** [comment]
I performed another test with strm files, still perfect on my setup.
Please post the strm file names and it's content for review.
