### ISSUE TITLE
Posters and other artwork often incomplete in Kodi

### ISSUE THREAD

**Issue by phantom-voltage** [MediaBrowser/plugin.video.emby#46]
I notice from time to time several posters grabbed from the Emby server are incomplete. The only way to fix this is to recache all artwork in the Emby add-on options, but this results in different posters and artwork having the same problem.

Posters are often partially there, with the rest being light grey. It appears that the transfer was interrupted.

I have the Emby option to force artwork cache on, and I tried limiting the number of requests, but the issue still remains. If I could individually recache certain artwork that would be great, but going into the artwork options in Kodi, I am only shown the same broken artwork files.

Emby Server Version 3.0.5973.0
Emby for Kodi Version 2.2.12
Kodi Version 16.1 Git:c327c53

EDIT: I'm trying to recache now with limited image_cache_threads. I'll report back if this solved the problem.

EDIT2: Everything looks good. Think the raspberry pi text for the option threw me off.

**Comment by angelblue05** [comment]
I'm glad you managed to fix this - How could we improve the text? Let me know.

**Comment by phantom-voltage** [comment]
Hey, thanks. It's probably not a big deal, looking back at it I don't see much wrong, but I instinctively ignored it because I wasn't using an rpi, but an Intel NUC. I'm not sure if it's specifically a problem for low performance PC's.  The Intel NUC performs quite well, so maybe have by default a limit to the thread count, even a rather high one.

**Comment by angelblue05** [comment]
I think what you were seeing is Kodi caching (it happens naturally, as you scroll...of course this happens more slowly on low powered devices) versus the add-on forcing to cache all artwork as the content is added to the Kodi database. This allows the artwork to display instantly.

**Comment by faush01** [comment]
The thread count limit is not there just for the clients, while it can and does help slow clients and stops the  addon overloading the client os with too many threads it can also stop issues with overloading the server with to many image requests. Perhaps what you were seeing was a server issue.

**Comment by angelblue05** [comment]
I think we should make the setting default to 25 instead of unlimited. What do you think?

**Comment by faush01** [comment]
It will be slower but probably more stable.
