### ISSUE TITLE
no access to server with latest 2.2.29 beta on Raspberry Pi 3

### ISSUE THREAD

**Issue by RealTabman** [MediaBrowser/plugin.video.emby#61]
After the Emby plugin updated automatically (I made a new Kodi profile to test something and the plugin auto updated before I could disable  auto-update), the connection to my Emby server was refused.
After reverting to 2.2.25, and rebooting, connection was established again automatically without problems.
The relevant part (at least I think so) of the log can be found here on pastebin:
http://pastebin.com/UH9VbAkt

Some more info:
My Emby Server is behind a restrictive Firewall because the box is also my VPN gateway.
The local address is 192.168.0.103, which I usually use since LAN access is not restricted by the Firewall.
The IP I got from my ISP is 10.4.13.140 (dynamic IP, changes at every connect). The firewall is only open to three ports on that IP, excluding 8096
Plus the exit IP from the VPN which depends on the current VPN server.
After the update to 2.2.29 I entered the IP 192.168.0.103 (and network credentials) manually and tried to connect again without success.

Kodi runs on a Raspberry Pi3 with the latest Libreelec.

**Comment by angelblue05** [comment]
Thanks for reporting. Can you give the latest beta 2.2.30 a try? Let me know if it resolves the issue.

**Comment by RealTabman** [comment]
Will do, but may take a few days before I find the time.

**Comment by RealTabman** [comment]
Just updated to beta 2.2.30 and I had no problem connecting to my Emby server even though Kodi crashed during the first reboot after updating. Of course, Kodi on Libreelec isn't exactly the most stable of programs, so this crash may not actually have anything to do with Emby.
Anyway, the second time Kodi booted without any obvious problems and the Emby add-on connected as usual.
There is one little nitpick though: in the Emby settings the "Primary Server Address" now displays the actual name of the server instead of the numeric IP address. Is it maybe possible to get the display of the actual IP address back somewhere?

**Comment by angelblue05** [comment]
Thanks for reporting back that it works.

For the primary server address, I was debating exposing the address because the field can be modified. Since everything is done automatically, I think having the server name as reference is enough information. I will think about re-exposing the address... Thanks for the feedback.
