### ISSUE TITLE
Sync is not passing the year of the movie to Kodi

### ISSUE THREAD

**Issue by bartolomesoriano** [MediaBrowser/plugin.video.emby#62]
I am using the latest plugin version from the develop branch, and Kodi Krypton Beta 2.  Did a new installation of the plugin with an empty Kodi db.  None of the movies have the year populated, even though it is correctly populated in Emby server.  TV Shows are not affected.

**Comment by angelblue05** [comment]
Krypton is not supported until RC. But will keep it in mind when we do support it.
