### ISSUE TITLE
Stacked movies: only the part 1 played

### ISSUE THREAD

**Issue by vores8** [MediaBrowser/plugin.video.emby#77]
I am using latest plugin from 1.0.3 repo with openelec 6.0.3. I have a movie which consists of 2 parts, named according to emby naming conventions. In Kodi it is shown as a single movie, as expected. But when I play this movie, only the 1st part is played and then Kodi complains that it cannot find next file to play.
More details
Library on Embe server is located at 
`/media/078cb749-d284-4bc0-a34e-000073f1e3d0/movies`
This path has a path substitution to `\\192.168.1.250\фильмы`

Movie itself is located in the library in the folder 
`/media/078cb749-d284-4bc0-a34e-000073f1e3d0/movies/чародеи`

Movie parts are 
`/media/078cb749-d284-4bc0-a34e-000073f1e3d0/movies/чародеи/movie-pt1.avi`
`/media/078cb749-d284-4bc0-a34e-000073f1e3d0/movies/чародеи/movie-pt2.avi`

As you can see from the attached log, it corrrectly starts playing the 1st part from the smb share

`09:18:47 T:140113653131136  NOTICE: DVDPlayer: Opening: smb://192.168.1.250/фильмы/чародеи/movie-pt1.avi `                                                                                                             

but when it comes to the 2nd part, the plugin does not use path substitution, trying to open the file from emby server local share
`09:18:57 T:140113653131136  NOTICE: DVDPlayer: Opening: /media/078cb749-d284-4bc0-a34e-000073f1e3d0/movies/чародеи/movie-pt2.avi`

of course this fails cause Kodi and Emby are different machines
`09:18:57 T:140112170538752   ERROR: CDVDPlayer::OpenInputStream - error opening [/media/078cb749-d284-4bc0-a34e-000073f1e3d0/movies/чародеи/movie-pt2.avi]`                                                                                      

[log.txt](https://github.com/MediaBrowser/plugin.video.emby/files/660926/log.txt)

**Comment by angelblue05** [comment]
Stacked movies are not supported when using native playback mode. The support is not great in Emby, therefore it's next to impossible for us to properly support this in Kodi. Stacked movies is only supported if you use Add-on playback mode. You'll get a much more stable experience with all Emby apps if you merge your stacked movies into one video file.

Sorry that it took long to get back to you on this. Please post here for faster support: https://emby.media/community/index.php?/forum/99-kodi/
