### ISSUE TITLE
Strange sort order in movie list

### ISSUE THREAD

**Issue by vores8** [MediaBrowser/plugin.video.emby#78]
My movie library contains movies with numeric/latin/cyrillic names and also several movie collections named in cyrillic. When the library displayed in Kodi (sort by name) it shows
`numerical movie names (like 2012)` then
`movie names from latin characters (like Jesus Christ Superstar)` then
`collections with cyrillic names` then
`movies with cyrillic names`

for me, this is a bit strange, cause I expect to see collections sorted in ascii order and then movies sorted in ascii order. In my case the sorted list should look like
`collections with cyrillic names` then
`numerical movie names (like 2012)` then
`movie names from latin characters (like Jesus Christ Superstar)` then
`movies with cyrillic names`

**Comment by angelblue05** [comment]
What is the default behavior in Kodi? The add-on doesn't sort items. Your content is added to the Kodi library, so Kodi really handles everything, the only exception being if you are using Add-on playback, then the add-on will simply provide the path to file to Kodi at the moment of playback. So you see, this is not really something to do with Emby with Kodi, unless you tell me the normal sort in Kodi is like what you expect.
