### ISSUE TITLE
Kodi 17 Beta crashes on initial sync in Addon Mode

### ISSUE THREAD

**Issue by Krautmaster** [MediaBrowser/plugin.video.emby#82]
-> 2.3.46 forces kodi to crash if "force artwork cache" is enabled, which is by default.

I turned it off and fine.

https://1drv.ms/u/s!Ar_eIBtD4lGqhMgyCKYQmhfnmxBqtQ

**Comment by faush01** [comment]
try setting it to a low number of threads

**Comment by Krautmaster** [comment]
I think i tried even a single thread. Only disabling the artwork cache fixed it for the first intial sync. Ill try to reproduce.
