### ISSUE TITLE
Artwork caching forces Kodi to crash away

### ISSUE THREAD

**Issue by Krautmaster** [MediaBrowser/plugin.video.emby#83]
kodi crashes within processing the emby movies randomly. In Kodi Emby settings, i just disabled artwork sync and it seems to be more stable now. At least im able to browse the movies now.

Kodi 17 RC
Emby 2.3.46

Logs:
https://1drv.ms/u/s!Ar_eIBtD4lGqhMgyCKYQmhfnmxBqtQ

**Comment by komodo2** [comment]
I am seeing this same issue. Had to disable "Force artwork caching" and all is well. Limiting cache threads did not help.

**Comment by pimlie** [comment]
Also encountering this issue on LibreElec v8.0.1 with the stable Emby Kodi repository.

Relevant log file entries:
```
17:51:34.875 T:1763701664  NOTICE: EMBY.artwork -> Waiting for empty queue spot: 25
17:51:52.347 T:2063070112  NOTICE: Previous line repeats 172 times.
17:51:52.347 T:2063070112  NOTICE: SpawnThread - fatal error creating thread
17:51:52.362 T:1763701664  NOTICE: EMBY.artwork -> Waiting for empty queue spot: 25
############### END LOG FILE ################
############ END kodi CRASH LOG #############
```
```
18:20:00.296 T:1584395168  NOTICE: EMBY.artwork -> Waiting for empty queue spot: 25
18:20:26.009 T:907015072  NOTICE: Previous line repeats 254 times.
18:20:26.010 T:907015072  NOTICE: SpawnThread - fatal error creating thread
18:20:26.053 T:1584395168  NOTICE: Previous line repeats 3 times.
############### END LOG FILE ################
############ END kodi CRASH LOG #############
```

**Comment by angelblue05** [comment]
Thank you for the feedback, we will continue to improve that area. 
Please for faster support in the future, post here: https://emby.media/community/index.php?/forum/99-kodi/
