### ISSUE TITLE
HTTP Basic Authentication partially working

### ISSUE THREAD

**Issue by firedomain** [MediaBrowser/plugin.video.emby#94]
I currently have a reverse proxy set up & am using a basic auth username/password with all my services.
accessing emby via the webpage works fine, but using the kodi addon only partially works.
When running the emby kodi setup i enter https://username:password@mydomain.com,
after entering the address/port the user page pops up & shows my users, so obviously it connected. but after i tap a user the user window closes & it does not ask for my user password.
is there any way for me to get basic authentication working with the kodi addon? i would really like to not have to open the emby page to the internet.

**Comment by angelblue05** [comment]
Can you post here with your Kodi log: https://emby.media/community/index.php?/forum/99-kodi/
I believe it should ask you for a password, that's how it normally works. I'll look into it once you post your log so I can see what Emby for Kodi is doing at that time. Thanks.
