### ISSUE TITLE
Can't connect to repository

### ISSUE THREAD

**Issue by Sparh4wk** [MediaBrowser/plugin.video.emby#96]
Hi,

just purchased a new tablet, and I cant install emby for kodi...

I can install repository, but not the addon :(

Any suggestions? 

Log included.
[kodi.txt](https://github.com/MediaBrowser/plugin.video.emby/files/1092543/kodi.txt)

**Comment by angelblue05** [comment]
@Sparh4wk 
I am so sorry to get back to you so late. Please post in our forums for faster support (no one is really looking at github). https://emby.media/community/index.php?/forum/99-kodi/

It looks like you are trying trouble installing dependencies. Could be requests that's causing the issue.
Follow the steps here: https://github.com/MediaBrowser/plugin.video.emby/wiki/Emby-Repository
Once the source is added, go to install from zip > the new emby source > public testing > dependencies. Install requests, then try to install the add-on again. That should resolve your issue.
