### ISSUE TITLE
Enhancement: mode=setusers&userlist=user1,user2

### ISSUE THREAD

**Issue by harrv** [MediaBrowser/plugin.video.emby#98]
### Introduction
Thank you for the plugin! My wife and I use it, Kodi, and Emby daily. I especially appreciate the ability to add and remove users from the session so that the Emby watched status and progress meters get updated for each user in the session. I have a `kodi` user that I configured to be the always-in-session plugin user, then I add or remove `steve` and/or `rachel` depending on who is watching.

To take advantage of that feature, I've programmed a button on my remote to call: 
```
RunPlugin(plugin://plugin.video.emby?mode=adduser)
```
### Drawbacks
The ability to do that with `mode=adduser` is convenient, but has a couple drawbacks:

1. No matter how it is triggered, mode=adduser requires a user to navigate a series of dialogs (first you bring up the dialog, then you select whether you're adding or removing a user, then you select the user that you are adding or removing from a list of displayed users). That's fine when a user initiates the action himself, but consider the case of home automation software. Some systems now include the ability to determine which household members are at home, or even in a particular room. Such a system *could* tie in to Emby for Kodi to automatically update the users who are in the current session, but not when user interaction is required (such as to navigate a dialog).

2. If an Emby user has been configured to `hide this user from login screens`, as I prefer to do with all of my users for privacy reasons, that user is not listed in the dialog that the Emby for Kodi plugin creates when adding a user to the session.

### Enhancement request
I believe that a solution to both of those issues could be to add a new dialog-less plugin mode for adding or removing users from the current session by explicitly setting a list of session users as a parameter of the URI in the RunPlugin command. I was thinking of something like this:
```
RunPlugin(plugin://plugin.video.emby?mode=setusers&userlist=steve,rachel)
```
A Kodi user could program that to a button on their remote, or an external automation process could call it directly, and it would not require a dialog or any additional input. If a user is already in the session but isn't specified in the new `userlist`, that user would be removed from the session (except for the always-in-session user the plugin requires). Likewise, if a user specified in `userlist` is not yet in the current session, he would be added.

### Conclusion
I think this could be quite helpful for those of us who like the idea of keeping watched data up to date for each Emby user who also uses Kodi, and who want to automate the process for updating the list of users in the session. Additionally, the ability to add session users who are hidden from login screens would be a big plus. I hope it is considered for implementation! Thanks!

P.S. I am a programmer and, although I am not strong with Python, I am tenacious about figuring stuff out. If the project owners think this enhancement request is a good idea, but the issue is at risk of being closed anyway simply because no active project developer has the time or inclination to implement it, then I'd welcome having a shot at it before it is closed.

**Comment by harrv** [comment]
Thinking about this some more, I examined addUser() in entrypoint.py in the plugin code to get an idea of how the plugin interfaces with the Emby server, and I see that it uses the Emby REST API to POST or DELETE a user from a session. I could probably do that too, for what I have in mind, instead of adding a new `setusers` mode to the plugin, as long as I could figure out the right session (looks like I need to know the deviceId to look that up). That Emby REST API used to be very nicely documented and viewable in a Swagger UI, but I haven't seen *any* Emby API doc (Swagger or not) for the better part of a year, so my efforts will be slowed by lack of doc. Nonetheless I think I have a path to the feature I want, probably without requiring an update to the Kodi plugin. So unless the dev team thinks implementing this as a plugin mode would be useful to a wider audience, this issue could be closed and I'll try working with the Emby REST API directly to do what I've asked for in this issue. Thanks.

**Comment by angelblue05** [comment]
I think you'll have better flexibility if you set this up as a standalone thing rather than directly adding it to the Emby for Kodi plugin. Then you could apply this to any Emby apps you might be using.

Feel free to post here if you need assistance with the API (since SWAGGER has been taken down and have no timeframe of when it's going to be back).
https://emby.media/community/index.php?/forum/47-developer-api/
